name: orround
description: "A new Flutter project."
publish_to: "none"
version: 0.1.1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  location: ^5.0.0
  geocoding: ^2.1.1
  http: ^1.1.0
  share_plus: ^7.2.1
  gal: ^2.1.3
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0
  uuid: ^4.0.0
  image_picker: ^1.0.7
  path_provider: ^2.1.1
  flutter_local_notifications: ^17.0.0
  flutter_foreground_task: ^8.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
